Script started on 2024-09-27 10:30:42-07:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="83" LINES="48"]
[?2004h[cliffpm@cancun cse374]$ echo $SHELL
[?2004l/bin/bash
[?2004h[cliffpm@cancun cse374]$ whoami
[?2004lcliffpm
[?2004h[cliffpm@cancun cse374]$ pwd
[?2004l/data/netid/cliffpm/cse374
[?2004h[cliffpm@cancun cse374]$ uname -a
[?2004lLinux cancun.cs.washington.edu 5.14.0-427.33.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 28 17:34:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[?2004h[cliffpm@cancun cse374]$ gcc --version -std=c11
[?2004lgcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[?2004h[cliffpm@cancun cse374]$ exit
[?2004lexit

Script done on 2024-09-27 10:31:25-07:00 [COMMAND_EXIT_CODE="0"]
